config/routes.rb
Rails.application.routes.draw do

  get 'workorders/index'

  get 'workorders/show'

  get 'workorders/new'

  get 'workorders/create'

  get 'workorders/delete'



  devise_for :users
  root to: 'home#index'


  resources :providers do
    resources :workorders, only: [:new, :create, :show]
  end

  resources :users, only: :show do
    resources :workorders, only: [:index, :show, :delete]
  end


  resources :profiles
  resources :settings

end

app/models/provider.rb
class Provider < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :service
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :workorders

  def self.search(service, address)
    if service
      near(address).where(service_id: service).order('id DESC')
    else
      order('id DESC')
    end
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  def index
    if params[:service].present? && params[:address].present?

      @providers = Provider.search(params[:service][:id], params[:address])

    else
      @providers = Provider.all
    end
      # @providers = Provider.where.not(latitude: nil, longitude: nil)
      @markers = @providers.map do |provider|
        {
          lat: provider.latitude,
          lng: provider.longitude#,
          # infoWindow: { content: render_to_string(partial: "/providers/map_box", locals: { flat: flat }) }
        }
      end
  end

  def show
    @provider_geo = [{
          lat: @provider.latitude,
          lng: @provider.longitude,
          range: @provider.range
        }]
  end

  def new
    @provider = Provider.new
    authorize @provider
  end

  def edit
  end

  def create
    @provider = Provider.new(provider_params)
    @provider.service = Service.find(provider_params[:service_id]) unless provider_params[:service_id] == ""
    @provider.user = current_user
    authorize @provider

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
      authorize @provider
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :address, :email, :phone_number, :presentation, :range, :photo, :service_id)
    end

    def article_params
      params.require(:article).permit(:title, :body, :photo)
    end
end

app/views/providers/_form.html.erb
<%= simple_form_for(@provider) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
    <%= f.input :presentation %>
    <%= f.input :range %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.association :service, prompt: "select service", include_blank: false %>
</div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">

      <%= render 'form', provider: @provider %>

      <%= link_to 'Show', @provider %> |
      <%= link_to 'Back', providers_path %>

    </div>
  </div>
</div>

app/views/providers/index.html.erb
<div class="top-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/2469/building-construction-building-site-constructing.jpg?w=940&h=650&dpr=2&auto=compress&cs=tinysrgb');">

  <div class= "top-banner-content" >
  <h1>Providers</h1>
 </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">




<% @providers.each do |provider| %>

  <div class="card" >

    <div class="message">

      <div class="message-name">
        <h3><%= link_to provider.name, provider  %></h3>
        <p><%= provider.service.name %></p>
      </div>

      <div class="message-body">
        <p><strong>Description</strong></p>
        <p><%= provider.phone_number %> <%= provider.email %></p>
        <p>
          <%= provider.presentation %>
        </p>
      </div>

     <%=  cl_image_tag provider.photo, height: 100, width: 100, crop: :fill,  class: "image_card" %>

    </div>
  </div>
  <br>

<% end %>

<%= link_to 'New Provider', new_provider_path %>
</div>

  </div>
</div>

app/views/providers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">

      <%= render 'form', provider: @provider %>

      <%= link_to 'Back', providers_path %>

    </div>
  </div>
</div>

app/views/providers/show.html.erb
<div class="top-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/2469/building-construction-building-site-constructing.jpg?w=940&h=650&dpr=2&auto=compress&cs=tinysrgb');">

  <div class= "top-banner-content" >

    <h2> <%= @provider.name %> : <%= @provider.service.name %> </h2>

  </div>
</div>

<div class="container">
  <div class="form-row">
      <div class="form-group col-md-6">
        <p><strong>Name:</strong> <%= @provider.name %></p>
        <p><strong>Address:</strong><%= @provider.address %></p>
        <p><strong>Email:</strong> <%= @provider.email %></p>
        <p><strong>Phone number:</strong><%= @provider.phone_number %></p>
        <p><strong>Presentation:</strong><%= @provider.presentation %></p>

        <p><strong>Range (km):</strong> <%= @provider.range %> </p>
        <p><strong>Service: </strong><%= @provider.service.name %></p>
        <p>
         <div><%= link_to "Book the service of this worker", new_provider_workorder_path(@provider), class:"indexlink btn btn-primary special_button" %>
         </div>

      <!--   <strong>Lat: </strong><%= @provider.latitude %> |
        <strong>Long: </strong><%= @provider.longitude %> -->
      </p>
    </div>


    <div class="form-group col-md-6">
      <%= cl_image_tag @provider.photo, height: 300, width: 300, crop: :fill %>
    </div>
  </div>

  <% if policy(@provider).edit? %>
  <%= link_to 'Edit', edit_provider_path(@provider) %> |
  <% end %>

  <% if policy(@provider).destroy? %>
  <%= link_to 'Destroy', @provider, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>

  <%= link_to 'Back', providers_path %>


  <br><br>
  <div
  id="map"
  data-markers="<%= @provider_geo.to_json %>"
  ></div>


</div>
</div>