config/routes.rb
Rails.application.routes.draw do

  get 'workorders/index'

  get 'workorders/show'

  get 'workorders/new'

  get 'workorders/create'

  get 'workorders/delete'



  devise_for :users
  root to: 'home#index'


  resources :providers do
    resources :workorders, only: [:new, :create, :show]
  end

  resources :users, only: :show do
    resources :workorders, only: [:index, :show, :delete]
  end


  resources :profiles
  resources :settings

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :set_profile

  def new
    @profile = Profile.new
  end

  def show
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to @profile, notice: 'Awesome'
    else
      render :new, errors: 'Something went wrong'
    end
  end

  def edit
  end

  def update
    @profile.update(profile_params)
    if @profile.save
      redirect_to @profile, notice: 'Updated'
    else
      render :new, errors: 'Something went wrong'
    end
    authorize @profile
  end

  def destroy
    @profile.destroy
    redirect_to :root_path
    authorize @profile
  end

  private

  def set_profile
    @profile ||= current_user.profile if current_user.profile
    authorize @profile

  end

  def profile_params
    params.require(:profile).permit(
      :name,
      :mobile,
      :title,
      :work_email
    )
  end
end

app/views/profiles/create.html.erb
<h1>Profile#create</h1>
<p>Find me in app/views/profile/create.html.erb</p>

app/views/profiles/destroy.html.erb
<h1>Profile#destroy</h1>
<p>Find me in app/views/profile/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<div class=“container”>
  <div class=“row”>
    <div class=“col-md-10 “>
      <form class=“form-horizontal”>
        <fieldset>

          <br>
          <div class=“form-group”>
            <label class=“col-md-4 control-label” for=“Name (Full name)“>Name (Full name)</label>
            <div class=“col-md-4”>
             <div class=“input-group”>
               <div class=“input-group-addon”>
                <i class=“fa fa-user”>
                </i>
              </div>
              <input id=“Name (Full name)” name=“Name (Full name)” type=“text” placeholder=“Name (Full name)” class=“form-control input-md”>
            </div>


          </div>


        </div>

        <!-- File Button -->
        <div class=“form-group”>
          <label class=“col-md-4 control-label” for=“Upload photo”>Upload photo</label>
          <div class=“col-md-4”>
            <input id=“Upload photo” name=“Upload photo” class=“input-file” type=“file”>
          </div>
        </div>



        <div class=“form-group”>
          <label class=“col-md-4 control-label col-xs-12" for=” Address”> Address</label>
          <div class=“col-md-2  col-xs-4">
            <input id=” Address” name=” Address” type=“text” placeholder=“District” class=“form-control input-md “>
          </div>

          <div class=“col-md-2 col-xs-4">

            <input id=” Address” name=” Address” type=“text” placeholder=“Area” class=“form-control input-md “>
          </div>


        </div>

        <div class=“form-group”>
          <label class=“col-md-4 control-label” for=” Address”></label>
          <div class=“col-md-2  col-xs-4">
            <input id=” Address” name=” Address” type=“text” placeholder=“Street” class=“form-control input-md “>

          </div>

        </div>


        <!-- Text input-->
        <div class=“form-group”>
          <label class=“col-md-4 control-label” for=” Occupation”> Occupation</label>
          <div class=“col-md-4”>
            <div class=“input-group”>
             <div class=“input-group-addon”>
               <i class=“fa fa-briefcase”></i>

             </div>
             <input id=” Occupation” name=” Occupation” type=“text” placeholder=” Occupation” class=“form-control input-md”>
           </div>


         </div>
       </div>


       <!-- Text input-->
       <div class=“form-group”>
        <label class=“col-md-4 control-label” for=“Phone number “>Phone number </label>
        <div class=“col-md-4”>
          <div class=“input-group”>
           <div class=“input-group-addon”>
             <i class=“fa fa-phone”></i>

           </div>
           <input id=“Phone number ” name=“Phone number ” type=“text” placeholder=“Primary Phone number ” class=“form-control input-md”>

         </div>
         <div class=“input-group othertop”>
           <div class=“input-group-addon”>
             <i class=“fa fa-mobile fa-1x” style=“font-size: 20px;“></i>
           </div>

           <input id=“Phone number ” name=“Secondary Phone number ” type=“text” placeholder=” Secondary Phone number ” class=“form-control input-md”>

         </div>

       </div>
     </div>

     <!-- Text input-->
     <div class=“form-group”>
      <label class=“col-md-4 control-label” for=“Email Address”>Email Address</label>
      <div class=“col-md-4”>
        <div class=“input-group”>
         <div class=“input-group-addon”>
           <i class=“fa fa-envelope-o”></i>

         </div>
         <input id=“Email Address” name=“Email Address” type=“text” placeholder=“Email Address” class=“form-control input-md”>

       </div>

     </div>
   </div>

   <!-- Text input-->
   <div class=“form-group”>
    <label class=“col-md-4 control-label” for=“Availability time”>Availability time</label>
    <div class=“col-md-4”>
      <div class=“input-group”>
       <div class=“input-group-addon”>
         <i class=“fa fa-clock-o”></i>

       </div>
       <input id=“Availability time” name=“Availability time” type=“text” placeholder=“Availability time” class=“form-control input-md”>

     </div>


   </div>
 </div>

 <!-- Text input-->
 <div class=“form-group”>
  <label class=“col-md-4 control-label” for=“Available Service Area”>Available Service Area</label>
  <div class=“col-md-4”>
    <div class=“input-group”>
     <div class=“input-group-addon”>
       <i class=“fa fa-street-view”></i>

     </div>
     <input id=“Available Service Area” name=“Available Service Area” type=“text” placeholder=“Available Service Area” class=“form-control input-md”>

   </div>


 </div>
</div>
<!-- Text input-->
<div class=“form-group”>
  <label class=“col-md-4 control-label” for=“License No.“>License No.</label>
  <div class=“col-md-4”>
    <div class=“input-group”>
     <div class=“input-group-addon”>
       <i class=“fa fa-sticky-note-o”></i>

     </div>
     <input id=“License No.” name=“License No.” type=“text” placeholder=“License No.” class=“form-control input-md”>

   </div>


 </div>
</div>

<!-- Text input-->
<div class=“form-group”>
  <label class=“col-md-4 control-label” for=“Working Experience (time period)“>Working Experience (time period)</label>
  <div class=“col-md-4”>
    <div class=“input-group”>
     <div class=“input-group-addon”>
       <i class=“fa fa-clock-o”></i>

     </div>
     <input id=“Working Experience (time period)” name=“Working Experience” type=“text” placeholder=“Enter time period ” class=“form-control input-md”>


   </div>

 </div>
</div>

<!-- Textarea -->
<div class=“form-group”>
  <label class=“col-md-4 control-label” for=“Overview (max 200 words)“>Overview (max 200 words)</label>
  <div class=“col-md-4”>
    <textarea class=“form-control” rows=“10”  id=“Overview (max 200 words)” name=“Overview (max 200 words)“>Overview</textarea>
  </div>
</div>


<div class=“form-group”>
  <label class=“col-md-4 control-label” ></label>
  <div class=“col-md-4”>
    <a href=“#” class=“btn btn-success”><span class=“glyphicon glyphicon-thumbs-up”></span> Submit</a>
    <a href=“#” class=“btn btn-danger” value=“”><span class=“glyphicon glyphicon-remove-sign”></span> Clear</a>

  </div>
</div>

</fieldset>
</form>
</div>
<div class=“col-md-2 hidden-xs”>
  <img src=“http://websamplenow.com/30/userprofile/images/avatar.jpg” class=“img-responsive img-thumbnail “>
</div>


</div>
</div>

app/views/profiles/show.html.erb
<br>
<br>

<p>Profile</p>

<div>
  <div class="card_profile">

    <div><img src="avatar.png"></div>


    <h1><%= @profile.name %></h1>

    <h2 class="title"><%= @profile.title %></h2>

    <p><%= @profile.mobile %></p>


    <p><%= @profile.work_email %></p>


    <div class="btn btn-primary">
      <p>
        <%=link_to 'Edit', edit_profile_path(current_user.profile) %>
      </p>
    </div>

    <div class="btn btn-primary delete_button">
      <p>
        <%=link_to 'Delete', root_path %>
      </p>
    </div>

  </div>
</div>

app/views/profiles/update.html.erb
<h1>Profile#update</h1>
<p>Find me in app/views/profile/update.html.erb</p>