config/routes.rb
Rails.application.routes.draw do

  get 'workorders/index'

  get 'workorders/show'

  get 'workorders/new'

  get 'workorders/create'

  get 'workorders/delete'



  devise_for :users
  root to: 'home#index'


  resources :providers do
    resources :workorders, only: [:new, :create, :show]
  end

  resources :users, only: :show do
    resources :workorders, only: [:index, :show, :delete]
  end


  resources :profiles
  resources :settings

end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin-in"></i></a>
  </div>
  <div class="footer-copyright">
    Everything you need <%= image_tag "logo.png", height: 15 %> you can have with FixIt
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
    <% unless params[:controller] == 'home' %>

    <%= form_tag(providers_path, method: :get, class: "form") do %>

    <%= text_field_tag :address %>
    <%= collection_select(:service, :id, Service.all, :id, :name, {prompt: 'Find a service'}) %>

    <%= submit_tag 'Search', class: "btn btn-primary" %>
    <% end %>
    <% end %>
    <!-- Links when logged in -->

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= current_user.email %>
            <%= image_tag "avatar.png",class: "avatar dropdown-toggle rounded-circle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"%>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <% if current_user.profile %>
            <%= link_to profile_path(current_user.profile) do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>